"use client";

import { Dream } from "./types";

export async function postDream(
  dreamtext: string,
  archetypeId: number
): Promise<boolean> {
  // TODO: Will actually be autoincremented and autogenerated by db
  const newDream: Dream = {
    dreamtext,
    archetypeId,
    id: Math.floor(Math.random() * 10000),
    date: new Date().toLocaleDateString("en-UK"),
  };

  const response = await fetch("/api/dream", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(newDream),
  });
  if (response.status < 300) return true;
  return false;
}
